export const KEYS = {
  ads: "ads",
  subSystem: "subsystem",
  group: "group",
  doc: "doc",
  news: "news",
  newsMain: "newsMain",
  workers: "workers",
  discuss: "discuss",
  appeal: "appeal",
  appealCategory: "appealCategory",
  structural: "structural",
  standards: "standards",
  buildingRegulations: "buildingRegulations",
};
