export const URLS = {
  ads: "ads/",
  subSystem: "shnk/subsystem",
  group: "shnk/group",
  doc: "shnk/doc",
  news: "news/",
  workers: "workers/",
  discuss: "discuss/",
  appeal: "appeal/",
  appealCategory: "appeal/appeal_category/",
  structural: "workers/structural/",
  standards: "shnk/standart/",
  buildingRegulations: "shnk/page/",
  shnqSubsystems: "shnk/subsystem/",
};
